<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework Condition="'$(MobileTargetFramework)' != ''">$(MobileTargetFramework)</TargetFramework>
        <TargetFramework Condition="'$(MobileTargetFramework)' == '' And '$(EnableAndroidTargeting)' == 'true'">net8.0-android34.0</TargetFramework>
        <TargetFramework Condition="'$(MobileTargetFramework)' == '' And '$(EnableAndroidTargeting)' != 'true'">net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NTextCat" Version="0.3.65" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.1" />
    </ItemGroup>
    <ItemGroup>
        <None Include="$(NuGetPackageRoot)ntextcat\0.3.65\content\LanguageModels\*.profile.xml"
              Link="LanguageModels\%(Filename)%(Extension)"
              CopyToOutputDirectory="PreserveNewest"
              CopyToPublishDirectory="PreserveNewest"
              Condition="Exists('$(NuGetPackageRoot)ntextcat\0.3.65\content\LanguageModels')" />
    </ItemGroup>

    <ItemGroup>
        <None Include="LanguageDictionaries\**\*.*"
              CopyToOutputDirectory="PreserveNewest"
              CopyToPublishDirectory="PreserveNewest"
              Condition="Exists('LanguageDictionaries')" />
    </ItemGroup>

</Project>
